# These github actions will perform linting using pre-commit.
# yamllint disable rule:line-length
# spell-checker: disable
---
name: pre-commit

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches-ignore:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: install talisman
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: thoughtworks/talisman
          extension-matching: disable
          rename-to: talisman
          chmod: 0755
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - uses: actions-rust-lang/setup-rust-toolchain
        with:
          components: clippy,rustfmt
      - uses: pre-commit/action@v3.0.1
